### ISSUE TITLE
Grade Requirements by percentage

### ISSUE THREAD

**Issue by kaohzina** [bcassellius/lovely-librarian#11]
# Technical Acceptance Criteria: 25%
- [x] Satisfies the following code requirements: Application uses React for the front end.
- [x] Application has a GraphQL, 
- [x] API, with a Node.js,
- [x] Express.js, 
- [x] server, 
- [ ] queries and mutations for retrieving, adding, updating, and deleting data.

- [x] Application uses MongoDB and the Mongoose ODM for the database and protects sensitive API key information on the server.
- [x] Application includes user authentication using JWT.

# Concept 10%
- [x] Application should originate from a unique and novel idea.
- [ ] Your group should clearly and concisely articulate your project idea.

# Deployment: 20%
- [x] Application deployed at live URL on Heroku and loads with no errors.
- [x] Application GitHub URL submitted.
- [ ] Portfolio at live URL submitted, featuring project.

# Repository Quality: 10%
- [x] Repository has a unique name.
- [x] Repository follows best practices for file structure and naming conventions.
- [x] Repository follows best practices for class and id naming conventions, indentation, quality comments, etc.
- [x] Repository contains multiple descriptive commit messages.
- [x] Repository contains a high-quality README file with description, screenshot, and link to deployed application.

# Application Quality: 15%
- [x] Application user experience is intuitive and easy to navigate.
- [x] Application user interface style is clean and polished.
- [x] Application is responsive.

# Presentation 10%
- [x] Your group should present using Google Slides, Powerpoint, or a similar presentation software.
- [x] Every group member should speak during the presentation.

# Collaboration 10%
- [x] There are no major disparities in the number of GitHub contributions among group members.

# Bonus
- [x] Fulfilling all three of the following requirements to turn your app into a PWA will add 10 points to your grade. Note that the highest grade you can achieve is still a 100:
- [x] Uses a web manifest
- [x] Uses a service worker for offline functionality
- [x] Is installable
 
# Due Date
Your group will work on this project over the course of the next two weeks.
Project presentations will take place during the second virtual class during the week of the next module, Module 24.
## The project itself is due on the final day of class with the group presentations. Each member of your group is required to submit the following for review:
The URL of the deployed application.
The URL of the GitHub repository, with a unique name and a README describing the project.
The URL of your portfolio, with your project added to it.
You’ll be able to submit your project assignment when you reach Module 24 next week.

**Comment by bcassellius** [comment]
Missing Mutations -->Agreed Upon by Group
