### ISSUE TITLE
--> Modified Feature -->Edit Staff Info

### ISSUE THREAD

**Issue by watkincw** [bcassellius/lovely-librarian#17]
- [ ] Job Role
- [ ] Email
- [ ] Editable "Likes":
- [ ] Staff members can make a like is things they like so that other members of the staff can cheer them up on tough days
- [ ] This is for CRUD Functionality
- [ ] This is a side panel. It should take up ~20% of the screen and disappear when the screen size becomes small. This is done in CSS @kaohzina

**Comment by bcassellius** [comment]
Staff Directory Page is working!  Future Development --> Add Edit and CRUD functionality
